targets:
  $default:
    builders:
      flutter_app_agree_annimation|route_parse_builder:
        enabled: true
        generate_for:
          exclude: ['**.internal.dart']
      flutter_app_agree_annimation|router_builder:
        enabled: true
        generate_for:
          exclude: ['**.internal.dart']

builders:
  router_builder:
    import: 'package:flutter_app_agree_annimation/agreerouter/builder.dart'
    builder_factories: ['routerBuilder']
    build_extensions: { '.router.dart': ['.internal.dart'] }
    auto_apply: root_package
    build_to: source

  route_parse_builder:
    import: 'package:flutter_app_agree_annimation/agreerouter/builder.dart'
    builder_factories: ['routeParseBuilder']
    build_extensions: { '.dart': ['.empty.dart'] }
    auto_apply: root_package
    runs_before: ['flutter_app_agree_annimation|router_builder']
    build_to: source